FROM alpine:latest

RUN apk add --no-cache bash curl

# actionlintをインストール
RUN curl -sL https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash | bash -s -- latest /usr/local/bin

WORKDIR /repo
ENTRYPOINT ["actionlint"]
